# Generated by Django 3.1.3 on 2021-04-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updateDate',
            field=models.DateField(auto_now=True),
        ),
    ]
