# Generated by Django 3.1.3 on 2021-04-13 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0002_auto_20210413_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-creatTime']},
        ),
        migrations.AddField(
            model_name='post',
            name='creatTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
