# Generated by Django 3.1.3 on 2021-04-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0006_auto_20210413_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
