# Generated by Django 3.1.3 on 2021-04-14 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0007_auto_20210414_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creatTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
