# Generated by Django 3.1.3 on 2021-04-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0012_auto_20210416_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
