# Generated by Django 3.1.3 on 2021-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikah', '0013_auto_20210416_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.CharField(default=' ', max_length=1500),
        ),
    ]
