# Generated by Django 3.1.5 on 2021-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210410_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicFour',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicOne',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicThree',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicTwo',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='profilepics'),
        ),
    ]
