# Generated by Django 3.1.3 on 2021-04-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='galleryPicFour',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='galleryPicOne',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='galleryPicThree',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='galleryPicTwo',
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
