# Generated by Django 3.1.3 on 2021-04-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210416_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skinTone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('পুরুষ', 'পুরুষ'), ('মহিলা', 'মহিলা'), ('অন্যান্য', 'অন্যান্য')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(choices=[('ইসলাম', 'ইসলাম'), ('সনাতন', 'সনাতন'), ('বৌদ্ধ', 'বৌদ্ধ'), ('খ্রিষ্টান', 'খ্রিষ্টান'), ('অন্যান্য', 'অন্যান্য')], default='', max_length=50),
        ),
    ]
