# Generated by Django 3.1.3 on 2021-04-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='galleryPicFour',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='galleryPicOne',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='galleryPicThree',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='galleryPicTwo',
            field=models.ImageField(default='profilepics/default.jpg', upload_to='gallerypics'),
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
