# Generated by Django 3.1.3 on 2021-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210416_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicFour',
            field=models.ImageField(default='profilepics/default.png', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicOne',
            field=models.ImageField(default='profilepics/default.png', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicThree',
            field=models.ImageField(default='profilepics/default.png', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='galleryPicTwo',
            field=models.ImageField(default='profilepics/default.png', upload_to='gallerypics'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(default='profilepics/default.png', upload_to='profilepics'),
        ),
    ]
